### ISSUE TITLE
make sure the values of @ref and @xml:id are matching

### ISSUE THREAD

**Issue by csae8092** [ArchiveTFMVienna/Rundbriefe#4]
e.g.  currently 
```xml
<principal>
      <rs ref="#patrick_aprent" type="person">Patrick Aprent</rs>
</principal>
```
does not match
```xml
<person xml:id="aprent_patrick">
    <persName ref="https://orcid.org/0000-0002-0359-5981">
        <surname>Aprent</surname>
        <forename>Patrick</forename>
    </persName>
</person>
```

**Comment by KlausIllmayer** [comment]
indeed - we agreed to define the identifier for persons to "surname_firstname". so we changed this in the "listperson.xml". but we didn't come to the point of applying it to the Rundbriefe-xml-files (and I forgot to mention it). so thanks for reminding.
